apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-basic-pvc
  labels:
    app: mysql-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
